# Site settings
title: Dana Cho 
header-img: img/home-bg.png
email: im.dana@gmail.com
copyright_name: imdanaaa
description: > # this means to ignore newlines until "baseurl:"
  Subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: imdanaaa
github_username:  imdanaaa
learn_profile: imdanaaa
email_username: im.dana@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
